LootJS.modifiers((event) => {
    const artifacts = [
        "artifacts:anglers_hat", "artifacts:antidote_vessel", "artifacts:bunny_hoppers", "artifacts:charm_of_sinking", /*"artifacts:chorus_totem",*/ "artifacts:cloud_in_a_bottle", "artifacts:cowboy_hat", "artifacts:cross_necklace", "artifacts:crystal_heart", "artifacts:digging_claws", "artifacts:feral_claws", "artifacts:fire_gauntlet", "artifacts:flame_pendant", "artifacts:flippers", "artifacts:golden_hook", "artifacts:helium_flamingo", "artifacts:kitty_slippers", "artifacts:lucky_scarf", "artifacts:night_vision_goggles", "artifacts:novelty_drinking_hat", "artifacts:obsidian_skull", "artifacts:onion_ring", "artifacts:panic_necklace", "artifacts:pickaxe_heater", "artifacts:plastic_drinking_hat", "artifacts:pocket_piston", "artifacts:power_glove", "artifacts:rooted_boots", "artifacts:running_shoes", "artifacts:scarf_of_invisibility", "artifacts:shock_pendant", "artifacts:snorkel", "artifacts:snowshoes", "artifacts:steadfast_spikes", "artifacts:superstitious_hat", "artifacts:thorn_pendant", "artifacts:umbrella", "artifacts:universal_attractor", "artifacts:vampiric_glove", "artifacts:villager_hat", "artifacts:whoopee_cushion", "raccompat:acid_walker", "raccompat:desolate_pendant", "raccompat:polar_boot", "raccompat:vine_ring", "ramcompat:frost_robe", "ramcompat:stink_gland", "ramcompat:tendon_lump"
    ];
    const tables = [
        "minecraft:archaeology/desert_pyramid", "minecraft:archaeology/desert_well", "minecraft:archaeology/ocean_ruin_cold", "minecraft:archaeology/ocean_ruin_warm", "minecraft:archaeology/trail_ruins_common", "minecraft:archaeology/trail_ruins_rare", "betterarcheology:archeology/chest_buried_ruins_sand", "betterarcheology:archeology/chest_catacombs_combat", "betterarcheology:archeology/chest_catacombs_generic", "betterarcheology:archeology/chest_catacombs_golden", "betterarcheology:archeology/chest_catacombs_library", "betterarcheology:archeology/chest_catacombs_potion", "betterarcheology:archeology/chest_jungle_temple_equip", "betterarcheology:archeology/chest_jungle_temple_food", "betterarcheology:archeology/chest_jungle_temple_generic", "betterarcheology:archeology/chest_jungle_temple_treasure", "betterarcheology:archeology/chest_light_temple_book", "betterarcheology:archeology/chest_light_temple_generic", "betterarcheology:archeology/chest_light_temple_pillager", "betterarcheology:archeology/chest_light_temple_treasure", "betterarcheology:archeology/chest_loot_prototype", "betterarcheology:archeology/chest_mesa_ruins", "betterarcheology:archeology/chest_mott", "betterarcheology:archeology/chest_radiance_totem", "betterarcheology:archeology/chest_sculk_sword", "betterarcheology:archeology/chest_tumulus", "betterarcheology:archeology/chest_underwater", "betterarcheology:archeology/desert_sand", "betterarcheology:archeology/fossiliferous_dirt_chicken", "betterarcheology:archeology/fossiliferous_dirt_creeper", "betterarcheology:archeology/fossiliferous_dirt_guardian", "betterarcheology:archeology/fossiliferous_dirt_jungle", "betterarcheology:archeology/fossiliferous_dirt_sheep", "betterarcheology:archeology/fossiliferous_dirt_villager", "betterarcheology:archeology/fossiliferous_dirt_wolf", "betterarcheology:archeology/loot_catacombs_equipment", "betterarcheology:archeology/loot_catacombs_generic", "betterarcheology:archeology/mesa_red_sand", "betterarcheology:archeology/plains_gravel", "betterarcheology:archeology/sussand_underwater", "betterarcheology:archeology/sword_loot", "betterarcheology:archeology/taiga_dirt"
    ];

    event.enableLogging();

    event
        .addLootTableModifier(tables)
        .randomChance(0.025)
        .addLoot(artifacts);
});