ServerEvents.recipes(event => {
  event.remove({ id: 'sophisticatedbackpacks:advanced_alchemy_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:alchemy_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:smithing_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:anvil_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:advanced_tool_swapper_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:tool_swapper_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:stack_upgrade_starter_tier' })
  event.remove({ id: 'sophisticatedbackpacks:stack_upgrade_tier_1' })
  event.remove({ id: 'sophisticatedbackpacks:stonecutter_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:auto_blasting_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:auto_blasting_upgrade_from_auto_smelting_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:auto_smoking_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:auto_smoking_upgrade_from_auto_smelting_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:smoking_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:blasting_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:smelting_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:auto_smelting_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:feeding_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:crafting_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:advanced_feeding_upgrade' })
  event.remove({ id: 'sophisticatedbackpacks:inception_upgrade' })
})
